name: loft

services:

  base:
    image: loft-base
    build:
      dockerfile: base.Dockerfile
    container_name: loft-base
    profiles: ["tools"]

  core:
    image: loft-core
    build:
      dockerfile: core.Dockerfile
    container_name: loft-core
    volumes:
      - ./workspaces:/loft/workspaces
      - /var/run/docker.sock:/var/run/docker.sock

  spass:
    image: loft-prover-spass
    build: ./provers/spass
    container_name: loft-prover-spass
    profiles: ["tools"]

  vampire:
    image: loft-prover-vampire
    build: ./provers/vampire
    container_name: loft-prover-vampire
    profiles: ["tools"]

  e:
    image: loft-prover-e
    build: ./provers/e
    container_name: loft-prover-e
    profiles: ["tools"]

  iprover:
    image: loft-prover-iprover
    build: ./provers/iprover
    container_name: loft-prover-iprover
    profiles: ["tools"]

  tptp-checker:
    image: loft-tptp-checker
    build: ./tools/tptp-checker
    container_name: loft-tptp-checker
    profiles: ["tools"]
