name: loft

services:

  # Base and core images

  base:
    image: loft-base
    build:
      dockerfile: base.Dockerfile
    container_name: loft-base
    profiles: ["tools"]

  core:
    image: loft-core
    build:
      dockerfile: core.Dockerfile
    container_name: loft-core
    volumes:
      - ./workspaces:/loft/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

  # Provers

  spass:
    image: loft-prover-spass
    build: ./provers/spass
    container_name: loft-prover-spass
    profiles: ["tools"]

  vampire:
    image: loft-prover-vampire
    build: ./provers/vampire
    container_name: loft-prover-vampire
    profiles: ["tools"]

  e:
    image: loft-prover-e
    build: ./provers/e
    container_name: loft-prover-e
    profiles: ["tools"]

  iprover:
    image: loft-prover-iprover
    build: ./provers/iprover
    container_name: loft-prover-iprover
    profiles: ["tools"]

  prover9:
    image: loft-prover-prover9
    build: ./provers/prover9
    container_name: loft-prover-prover9
    profiles: ["tools"]

  # TPTP checker and converters

  tptp-checker:
    image: loft-tptp-checker
    build: ./tools/tptp-checker
    container_name: loft-tptp-checker
    profiles: ["tools"]

  cnf:
    image: loft-converter-cnf
    build: ./tools/cnf
    container_name: loft-converter-cnf
    profiles: ["tools"]

  ladr:
    image: loft-converter-ladr
    build: ./tools/ladr
    container_name: loft-converter-ladr
    profiles: ["tools"]
